version: "3"

services:
  nginx-proxy:
    image: secomm/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  nginx-proxy-letsencrypt:
    image: 'jrcs/letsencrypt-nginx-proxy-companion'
    container_name: nginx-proxy-letsencrypt
    volumes:
      - ./certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
volumes: 
  vhostd:

networks: 
  default:
    external:
      name: reverse-proxy
